"use client";
import { Sidebar, SidebarItem, SidebarItemGroup, SidebarItems } from "flowbite-react";
import { Avatar } from "flowbite-react";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-row`}
      >

     

          <Sidebar aria-label="Default sidebar example" className="h-screen">

            <div className="flex flex-wrap gap-2">
              <Avatar img="/avatar.avif" alt="avatar of Jese" size="xl" rounded className="mx-auto" />
            </div>

            <SidebarItems>
              <SidebarItemGroup>
                <SidebarItem href="/" >
                  Home
                </SidebarItem>
                <SidebarItem href="/projects">
                  Projects
                </SidebarItem>
                <SidebarItem href="/blogs">
                  Blogs
                </SidebarItem>
                <SidebarItem href="/cv" >
                  CV
                </SidebarItem>
                <SidebarItem href="/contact" >
                  Contact
                </SidebarItem>
              </SidebarItemGroup>
            </SidebarItems>
          </Sidebar>



        {children}
      </body>
    </html>
  );
}
